//
//key_party Class Declaration
//

#pragma once
class key_party
{
private:
	unsigned long iteration_;
	unsigned long initialkey_; //the initial value generated by the process
	unsigned long counterpartIKey_; //the initial key generated by this objects counterpart
	unsigned long finalkey_; //the final key generated by this object
public:
	//Constructor Destructor
	key_party();
	~key_party();
	

	//Mutators
	int setcounterpartIKey(unsigned long); //set counterparts initial key
	int setInitialKey(unsigned long); // 
	unsigned long generate_exchange(unsigned long, unsigned long); //performs the math required by Diffie-Hellman: raises the key value of this object to the selected prime mod a number

	//Accessors
	unsigned long getInitialKey(); //gets this objects initial key - generated by generate_exchange ()
	unsigned long getFinalKey(); //gets this objects final key - generated by generate_exchange ()

	//Predicate

};



